import './globals.css'
import ScrollToTop from '@/components/ScrollToTop'

export const metadata = {
  title: 'KOMO-YUKI | Modern Asian Gifts & Toys Retail Concept',
  description: 'Japanese-inspired retail designed for high-footfall town centres. Professional B2B presentation for landlords and property developers.',
  appleWebApp: {
    title: 'KOMO-YUKI',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Outfit:wght@400;600;700&family=Noto+Serif+JP:wght@300;400;500&family=Noto+Sans+JP:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
        {/* Favicons - Generated by RealFaviconGenerator.net */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#f6bcc8" />
        <meta name="apple-mobile-web-app-title" content="KOMO-YUKI" />
        <meta name="application-name" content="KOMO-YUKI" />
        <meta name="msapplication-TileColor" content="#f6bcc8" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="antialiased">
        <ScrollToTop />
        {children}
      </body>
    </html>
  )
}
